smartparking/parking/urls.py
from django.urls import path
from parking import views


urlpatterns = [    
    path('', views.home,name="home"),
    path('parkingslots/<int:pk>/',views.parkingslots,name="parkingslots"),
    path('parkingslots/<int:pk>/bookslot/', views.bookslot,name="book_slot"),
    path("bookingslot/booking-comfirm/",views.comfirm_booking,name="comfirm_booking"),
     path("parkingslots/active-slots/",views.active_slots,name="active_slots"),
    path("bookingslot/booking-expired/",views.booking_expired,name="booking_expired"),
]

smartparking/smartparking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from parking import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('parking.urls')),
    path('payements/',include('payements.urls',namespace="payements")),
    path('useraccounts/',include('useraccounts.urls',namespace="useraccounts")),
 
]


if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

smartparking/useraccounts/urls.py
from django.urls import path
from useraccounts import views

app_name="useraccounts"
urlpatterns = [    
    path('register/', views.register,name="register"),
    path('login/', views.login,name="login"),
    path('logout/', views.logout,name="logout"),
    path("user-profile/",views.user_profile,name="user_profile")
]

smartparking/templates/includes/booking_model.html
 <!-- Modal Structure for booking-->
  <div id="slot-{{slot.id}}" class="modal">
    <div class="modal-content">
      <div class="row" >
        <form  name="slot-form-{{slot.id}}" class="col s12" id="bookings-details-form-{{slot.id}}"  method="POST" enctype="multipart/form-data">
         
          {% csrf_token %}
 
          <div class="row">
            <div class="input-field col s12">
              <input id="car-model" type="text" name="car-model" class="validate">
              <label for="car-model">Car Model</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <input id="car-number-plate" type="text" name="number-plate" class="validate">
              <label for="car-number-plate">Car Number plate</label>
            </div>
          </div>
          <div class="row"></div>
          <div class="row">
            <div class="input-field col s12 ">
              <input type="text"  class="timepicker" name="start" placeholder="starting time">
              
            </div>
          </div>
          
          <div class="row">
            <div class="input-field col s12">
              <input type="text"  class="timepicker" name="end" placeholder="ending time">
              
            </div>
          </div>
         
         <a  class="modal-action  waves-effect waves-green btn-flat center" id="book-button" data-slot_id="{{slot.id}}">Book Slot</a>
        </form>
      </div>
    </div>
  </div>
 

smartparking/templates/includes/head.html
{% load static %}
<head>
<!--Import Google Icon Font-->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
 <!-- Compiled and minified CSS -->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
 <!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<link rel="stylesheet" href="{% static 'css/spinner.css' %}">
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

smartparking/templates/includes/js.html
{% load static %}
<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
 <!-- importing axios   -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<!-- custom file imports -->

<!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="https://www.gstatic.com/firebasejs/8.0.1/firebase.js"></script>

<!-- custom js files -->
<script src="{% static 'js/global_constants.js' %}" ></script>
<script  src="{% static 'js/helpers.js' %}" ></script>
<script src="{% static 'js/modal.js' %}" ></script>
<script src="{% static 'js/login_form_handler.js' %}"></script>
<script src="{% static 'js/bookings_form_handler.js' %}"></script>
<script src="{% static 'js/create_account_form_handler.js' %}"></script>
<script src="{% static 'js/logout.js' %}"></script>
<script src="{% static 'js/booking_time_handler.js' %}"></script>
<script src="{% static 'js/firebaseConfig.js' %}" ></script>
<script src="{% static 'js/live_slot_monitoring.js' %}" ></script>

smartparking/templates/includes/modals.html
<!-- Modal Structure login-->
<div id="login" class="modal">
  <div class="modal-content">
    <form  id="login-form" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row">
        <div class="row">
          <div class="input-field col s12">
            <input id="email" name="username" type="text" class="validate">
            <label for="email">Username</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <input id="password" name="password" type="password" class="validate">
            <label for="password">Password</label>
          </div>
        </div>
      </div>
      
    </form>
  </div>
  <div class="modal-footer">
    <a  class="modal-action modal-close waves-effect waves-green btn-flat " id="login-button-close">Close</a>
    <a  class="modal-action  waves-effect waves-green btn-flat" id="login-button">Login</a>
  </div>
</div>


<!-- create-account modal -->
<div id="create-account" class="modal">
  <div class="modal-content">
    <form  id="create-account-form" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row">
        <div class="row">
          <div class="input-field col s12">
            <input id="username" name="username" type="text" class="validate">
            <label for="username">Username</label>
          </div>
        <div class="row">
          <div class="input-field col s12">
            <input id="email" name="email" type="email" class="validate">
            <label for="email">Email</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <input id="password" type="password" name="password" class="validate">
            <label for="password">Password</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <input id="password" name="password2" type="password" class="validate">
            <label for="password">Comfirm Password</label>
          </div>
        </div>
      </div>
      
    </form>
  </div>
  <div class="modal-footer  center-align-text">
    <a  class="modal-action modal-close waves-effect waves-green btn-flat create-account-button-close">Close</a>
    <a  class="modal-action  waves-effect waves-green btn-flat" id="create-account-button">Create Account</a>
  </div>
</div>

smartparking/templates/includes/navbar-list.html
{% if request.user.is_authenticated %}
    
    <li><a href="{% url 'useraccounts:user_profile' %}"> <i class="material-icons">person</i><span>Account</span></a></li>
    <li><a   onclick="confirmalert();"> <i class="material-icons">thumb_down</i><span>Logout</span></a></li>
    <li><a href="{% url 'active_slots' %}">Active Slots</a></li>
{% else %}

    <li><a class="modal-trigger" href="#login"><i class="material-icons medium">thumb_up</i><span>Login</span></a></li>
    <li><a href="#create-account" class="modal-trigger"> <i class="material-icons medium">person_add</i><span>Account</span></a></li>

{% endif%}

smartparking/templates/includes/navbar.html
<div class="navbar-fixed"">
    
<nav >
    <div class="nav-wrapper  #64b5f6 blue lighten-2">
        <!-- <a href="{%url 'home' %}" class="brand-logo center">IPARKS</a> -->
        {% if request.session.booking_period %}
         <a href="{%url 'home' %}" class="brand-logo center duration">IPARKS</a>
        {% else %}
         <a href="{%url 'home' %}" class="brand-logo center duration">IPARKS</a>
        {% endif %}
        <a  data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            {% include 'includes/navbar-list.html' %}
        </ul>
        <ul class="side-nav" id="mobile-demo">
        <!--Login Modal Trigger -->
         {% include 'includes/navbar-list.html' %}
        </ul>
    </div>
    </nav>
</div>

smartparking/templates/includes/parking_ground_card.html
<!-- parking ground card -->
<div class="row ">
    <div class="col s12 m7 l10 offset-l1 offset-m2 ">
        <div class="card small  z-depth-0">
            <div class="card-image ground-img-wrapper">
                <img src="{{parking_ground.image.url}}">
                <span class="card-title card-title-text ground-name">{{parking_ground.name}}</span>
                <div id="overlay"></div> 
            </div>
            <div class="card-content  center">
                <p>Its high time you start booking for any slots available from your place of convenience</p>
                <p>Click on the link below to select any slot from this parking area</p>
            </div>
            <div class="center parking-ground-button  #64b5f6 blue lighten-2">
                <a href="{% url 'parkingslots' parking_ground.id %}" class="pulse">Parking Slots</a>
            </div>
        </div>
    </div>
</div>
    

smartparking/templates/includes/slot_card.html
<!-- slot card -->
<div class="card small z-depth-0 white">
  <div class="card-image waves-effect waves-block waves-light">
    <img src="{{slot.parking_ground.image.url}}">
    {% if not slot.booked %}
    <div class="card-title card-title-text " >
     {% if request.user.is_authenticated %}
      <a class="waves-effect waves-light btn modal-trigger booking-modal-triger #90caf9 blue lighten-3" href="#slot-{{slot.id}}">
       
        Book {{slot.name}}
      </a>
      {% else %}
      <a class="waves-effect waves-light btn modal-trigger booking-modal-triger #90caf9 blue lighten-3" href="#login">
       
        Login
      </a>
      {% endif %}
    </div>

    {% else %}
    <span class="card-title  card-title-text "><a class="waves-effect waves-light btn #d50000 red accent-4" >Booked</a></span>
    {% endif %}
  </div>
  <div class="card-content center">
      <span class="card-title activator grey-text text-darken-4">{{slot.name}}</span>
      <p>Book at only Ugx: {{slot.fee}}</p> 
      <p>Located on  {{slot.parking_ground.name}}</p>
      
  </div>
  {% include "includes/booking_model.html" with slot=slot %}
</div>

smartparking/templates/includes/spinner.html
<div class="spinner-wrapper" id="spinner-wrapper">
    <div class="loader ">Loading...</div>
</div>